import type { Metadata } from 'next'
import { Providers } from './providers'
import './globals.css'
import Footer from '@/components/Footer'

export const metadata: Metadata = {
  title: 'UA Tax calculator',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body>
        <Providers>
          <div className="min-h-screen flex flex-col items-center justify-between">
            <main className="max-w-5xl w-full grow p-8 lg:p-24">
              {children}
            </main>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  )
}
